### ISSUE TITLE
Does not work for latest Xcode.

### ISSUE THREAD

**Issue by dvcv** [ROKOLabs/ROKOmoji.iMessage.Sticker.App-iOS#1]
I get the following error when I try to run the simulator. 
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dvcv** [comment]
nevermind i was opening the wrong file

**Comment by jngnyc** [comment]
@dvcv - glad you were able to fix the issue. Don't hesitate to ping us here, or at help@rokolabs.com if you have any other issues!
